# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: helloworld.proto for package 'helloworld'

require 'grpc'
require 'helloworld_pb'

module Helloworld
  module API
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'helloworld.API'

      rpc :ListItem, ListItemRequest, ListItemResponse
      rpc :GetItem, GetItemRequest, Item
      rpc :AddItem, Item, AddItemResponse
      rpc :UpdateItem, UpdateItemRequest, UpdateItemResponse
      rpc :DeleteItem, DeleteItemRequest, DeleteItemResponse
    end

    Stub = Service.rpc_stub_class
  end
end
